---
spring.config.activate.on-profile: "local"

swagger.server.url: http://localhost:9001

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/v2/swagger
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  api-docs:
    path: /api/v2/v3/api-docs

---
spring.config.activate.on-profile: "dev"

swagger.server.url: ${SWAGGER_SERVER_URL}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/v2/swagger
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  api-docs:
    path: /api/v2/v3/api-docs

---
spring.config.activate.on-profile: prod
